// Runtime half of the wire-contract guard. The heavy lifting is compile-time:
// `__fixtures__/contract.gen.ts` (regenerated by `cargo test --lib`) annotates
// every Rust-serialized exemplar with its TS type, so `npm run build` fails on
// shape drift. These assertions make key-casing drift ALSO fail loudly at
// `npm test` — tsc alone can't catch a fixture regenerated with renamed keys
// until someone recompiles, and they document the two casing regimes.

import { describe, expect, it } from "vitest";
import * as fx from "./__fixtures__/contract.gen";

const keys = (o: object) => Object.keys(o);

describe("wire contract fixtures", () => {
  it("event payloads use camelCase keys", () => {
    expect(keys(fx.gitPayload)).toContain("workspaceId");
    expect(keys(fx.gitPayload)).toContain("diffStat");
    expect(keys(fx.gitPayload)).not.toContain("workspace_id");
    expect(keys(fx.sessionPayload)).toContain("awaitingInput");
    expect(keys(fx.sessionPayload)).toContain("needsAttention");
    expect(keys(fx.chatTurnEvent)).toContain("entrySeq");
    expect(keys(fx.chatTurnEvent)).toContain("endedAt");
    expect(keys(fx.notifyPayload)).toContain("taskTitle");
  });

  it("registry-backed command returns keep their legacy snake_case keys", () => {
    expect(keys(fx.workspace)).toContain("project_id");
    expect(keys(fx.workspace)).toContain("base_branch");
    expect(keys(fx.workspace)).toContain("autofix_mode");
    expect(keys(fx.prStatus)).toContain("head_branch");
    expect(keys(fx.serverInfo)).toContain("workspace_id");
  });

  it("enum wire spellings match the TS unions", () => {
    expect(fx.prCheck.bucket).toBe("failure");
    expect(fx.prStatus.rollup).toBe("failure");
    expect(fx.sessionPayload.activity).toBe("working");
    expect(fx.gitHubLoginEvent.phase).toBe("awaitingCode");
    expect(fx.workspace.autofix_mode).toBe("super");
  });

  it("nested chat entries carry the discriminants the UI switches on", () => {
    expect(fx.entries.map((e) => e.type)).toEqual([
      "user",
      "assistant",
      "system",
    ]);
    expect(fx.blocks.map((b) => b.type)).toEqual([
      "text",
      "reasoning",
      "tool",
      "file",
    ]);
  });
});
