// GENERATED by `cargo test --lib` — src-tauri/src/contract_fixtures.rs. Do not edit.
// Each exemplar is the serde serialization of a Rust wire DTO, annotated with
// its TS mirror type: `tsc` (npm run build) type-checking this file IS the
// Rust<->TS contract check. src/lib/contract.test.ts spot-checks key casing.
import type {
  Workspace,
  ProjectView,
  SidebarWorkspace,
  ChatSnapshot,
  Entry,
  Block,
  UsageInfo,
  ChatEntryEvent,
  ChatBlockEvent,
  ChatTurnEvent,
  ChatPermissionEvent,
  ChatConfigEvent,
  ChatResetEvent,
  ChatContextEvent,
  ChatCommandsEvent,
  ChatCommand,
  ConfigOption,
  GitPayload,
  SessionPayload,
  PrPayload,
  PrStatus,
  PrCheck,
  NotifyPayload,
  TodosPayload,
  Todo,
  WorkspaceSetupPayload,
  AccountsPayload,
  ReviewInboxPayload,
  GitHubLoginEvent,
  BoardSnapshot,
  ActivityEntry,
  UnlinkedTask,
  ServerInfo,
  ToolsStatus,
} from "../types";

export const workspace: Workspace = {
  "id": "ws-1",
  "project_id": "p1",
  "kind": "Worktree",
  "path": "/tmp/worktrees/p1/feature-x",
  "branch": "feature/x",
  "name": "Add dark mode",
  "base_branch": "main",
  "init_prompt": "Set up the workspace.",
  "autofix_mode": "super",
  "model": "anthropic/claude-opus-4-8",
  "effort": "high",
  "pr_number": 42,
  "pr_is_fork": true,
  "pr": {
    "number": 42,
    "url": "https://github.com/acme/repo/pull/42",
    "state": "OPEN",
    "head_branch": "feature/x",
    "head_sha": "abc123",
    "checks": [
      {
        "name": "test",
        "bucket": "failure",
        "state": "FAILURE",
        "url": "https://ci.example/run/1",
        "workflow": "CI"
      }
    ],
    "rollup": "failure"
  },
  "setup": "ready"
};

export const projectView: ProjectView = {
  "id": "p1",
  "name": "branchlab",
  "root_path": "/Users/me/code/branchlab",
  "default_branch": "main",
  "prompts": {
    "init_workspace": "Set up the new workspace.",
    "commit": "Stage all changes in this workspace with git add -A, then commit with a clear, concise conventional commit message that summarizes the diff. Do not push.",
    "merge": "Merge this workspace's branch into the base/main branch of the repository. First run the git commands from this workspace directory. Then switch to the base branch in the parent repository, merge this workspace's branch into it, and push the result to origin. Confirm the merge succeeded.",
    "push": "First, check the git diff to see what has changed in this workspace. If there is no clear branch name, invent one that fits the changes (e.g. feature/xxx, tech/xxx, fix/xxx, refactor/xxx, or similar). Then stage the logical changes with git add, commit with a clear conventional commit message, and push the branch to the origin remote. Confirm the remote and branch name.",
    "create_pr": "Push the current workspace branch to origin and open a GitHub pull request against the base branch using gh pr create. Use a clear title and description based on the changes."
  },
  "account_id": "github.com/octocat",
  "run": {
    "setup_script": "npm install",
    "teardown_script": "true"
  },
  "estimate_unit": "tshirt",
  "workspaces": [
    {
      "id": "ws-1",
      "project_id": "p1",
      "kind": "Worktree",
      "path": "/tmp/worktrees/p1/feature-x",
      "branch": "feature/x",
      "name": "Add dark mode",
      "base_branch": "main",
      "init_prompt": "Set up the workspace.",
      "autofix_mode": "super",
      "model": "anthropic/claude-opus-4-8",
      "effort": "high",
      "pr_number": 42,
      "pr_is_fork": true,
      "pr": {
        "number": 42,
        "url": "https://github.com/acme/repo/pull/42",
        "state": "OPEN",
        "head_branch": "feature/x",
        "head_sha": "abc123",
        "checks": [
          {
            "name": "test",
            "bucket": "failure",
            "state": "FAILURE",
            "url": "https://ci.example/run/1",
            "workflow": "CI"
          }
        ],
        "rollup": "failure"
      },
      "setup": "ready"
    }
  ]
};

export const sidebarWorkspace: SidebarWorkspace = {
  "workspaceId": "ws-1",
  "diffStat": {
    "files": 3,
    "insertions": 42,
    "deletions": 7
  },
  "session": {
    "workspaceId": "ws-1",
    "activity": "working",
    "awaitingInput": true,
    "needsAttention": true,
    "error": "the last turn failed"
  },
  "pr": {
    "workspaceId": "ws-1",
    "status": {
      "number": 42,
      "url": "https://github.com/acme/repo/pull/42",
      "state": "OPEN",
      "head_branch": "feature/x",
      "head_sha": "abc123",
      "checks": [
        {
          "name": "test",
          "bucket": "failure",
          "state": "FAILURE",
          "url": "https://ci.example/run/1",
          "workflow": "CI"
        }
      ],
      "rollup": "failure"
    },
    "phase": "awaiting_push",
    "attempts": 2,
    "mode": "super",
    "error": "poll failed"
  }
};

export const chatSnapshot: ChatSnapshot = {
  "entries": [
    {
      "type": "user",
      "seq": 1,
      "entryId": "u1",
      "display": "Fix the failing test",
      "sent": "Fix the failing test (expanded)",
      "attachments": [
        {
          "mime": "image/png",
          "url": "data:image/png;base64,AAAA",
          "filename": "shot.png"
        }
      ],
      "model": "anthropic/claude-opus-4-8",
      "variant": "high",
      "agent": "build",
      "origin": "user",
      "createdAt": 1700000000000
    },
    {
      "type": "assistant",
      "seq": 2,
      "entryId": "a1",
      "status": "completed",
      "origin": "autofix",
      "blocks": [
        {
          "type": "text",
          "blockId": "b1",
          "text": "Fixed the failing test."
        },
        {
          "type": "reasoning",
          "blockId": "b2",
          "text": "The bug is in config parsing…"
        },
        {
          "type": "tool",
          "blockId": "b3",
          "callId": "c3",
          "name": "edit",
          "title": "Edit config.rs",
          "status": "completed",
          "input": {
            "filePath": "src/config.rs"
          },
          "output": "ok",
          "diff": {
            "path": "src/config.rs",
            "oldText": "a",
            "newText": "b"
          },
          "locations": [
            {
              "path": "src/config.rs",
              "line": 88
            }
          ],
          "rawOutput": {
            "exitCode": 0
          },
          "startedAt": 1700000000000,
          "endedAt": 1700000001200
        },
        {
          "type": "file",
          "blockId": "b4",
          "name": "screenshot.png",
          "mime": "image/png",
          "url": "data:image/png;base64,AAAA"
        }
      ],
      "summary": {
        "collapsed": true,
        "stepCount": 3,
        "filesEdited": [
          "src/config.rs"
        ],
        "commandsRun": 1,
        "headline": "Edited 1 file · ran 1 command"
      },
      "usage": {
        "input": 1200,
        "output": 340,
        "reasoning": 80,
        "cacheRead": 9000,
        "cacheWrite": 100
      },
      "startedAt": 1700000000000,
      "endedAt": 1700000009000
    },
    {
      "type": "system",
      "seq": 3,
      "entryId": "s1",
      "kind": "success",
      "text": "PR #42 was merged — this workspace can be deleted.",
      "createdAt": 1700000000000,
      "steps": [
        {
          "label": "Run setup script",
          "status": "running",
          "log": [
            "$ npm install"
          ],
          "startedAt": 1700000000000,
          "endedAt": 1700000000500
        }
      ],
      "action": "deleteWorkspace"
    }
  ],
  "hasMore": true,
  "config": [
    {
      "id": "model",
      "name": "Model",
      "description": "The model driving the session",
      "category": "model",
      "currentValue": "anthropic/claude-opus-4-8",
      "choices": [
        {
          "value": "anthropic/claude-opus-4-8",
          "name": "Claude Opus 4.8",
          "description": "flagship",
          "group": "Anthropic"
        }
      ]
    }
  ],
  "commands": [
    {
      "name": "compress",
      "description": "Compress memory files"
    }
  ]
};

export const entries: Entry[] = [
  {
    "type": "user",
    "seq": 1,
    "entryId": "u1",
    "display": "Fix the failing test",
    "sent": "Fix the failing test (expanded)",
    "attachments": [
      {
        "mime": "image/png",
        "url": "data:image/png;base64,AAAA",
        "filename": "shot.png"
      }
    ],
    "model": "anthropic/claude-opus-4-8",
    "variant": "high",
    "agent": "build",
    "origin": "user",
    "createdAt": 1700000000000
  },
  {
    "type": "assistant",
    "seq": 2,
    "entryId": "a1",
    "status": "completed",
    "origin": "autofix",
    "blocks": [
      {
        "type": "text",
        "blockId": "b1",
        "text": "Fixed the failing test."
      },
      {
        "type": "reasoning",
        "blockId": "b2",
        "text": "The bug is in config parsing…"
      },
      {
        "type": "tool",
        "blockId": "b3",
        "callId": "c3",
        "name": "edit",
        "title": "Edit config.rs",
        "status": "completed",
        "input": {
          "filePath": "src/config.rs"
        },
        "output": "ok",
        "diff": {
          "path": "src/config.rs",
          "oldText": "a",
          "newText": "b"
        },
        "locations": [
          {
            "path": "src/config.rs",
            "line": 88
          }
        ],
        "rawOutput": {
          "exitCode": 0
        },
        "startedAt": 1700000000000,
        "endedAt": 1700000001200
      },
      {
        "type": "file",
        "blockId": "b4",
        "name": "screenshot.png",
        "mime": "image/png",
        "url": "data:image/png;base64,AAAA"
      }
    ],
    "summary": {
      "collapsed": true,
      "stepCount": 3,
      "filesEdited": [
        "src/config.rs"
      ],
      "commandsRun": 1,
      "headline": "Edited 1 file · ran 1 command"
    },
    "usage": {
      "input": 1200,
      "output": 340,
      "reasoning": 80,
      "cacheRead": 9000,
      "cacheWrite": 100
    },
    "startedAt": 1700000000000,
    "endedAt": 1700000009000
  },
  {
    "type": "system",
    "seq": 3,
    "entryId": "s1",
    "kind": "success",
    "text": "PR #42 was merged — this workspace can be deleted.",
    "createdAt": 1700000000000,
    "steps": [
      {
        "label": "Run setup script",
        "status": "running",
        "log": [
          "$ npm install"
        ],
        "startedAt": 1700000000000,
        "endedAt": 1700000000500
      }
    ],
    "action": "deleteWorkspace"
  }
];

export const blocks: Block[] = [
  {
    "type": "text",
    "blockId": "b1",
    "text": "Fixed the failing test."
  },
  {
    "type": "reasoning",
    "blockId": "b2",
    "text": "The bug is in config parsing…"
  },
  {
    "type": "tool",
    "blockId": "b3",
    "callId": "c3",
    "name": "edit",
    "title": "Edit config.rs",
    "status": "completed",
    "input": {
      "filePath": "src/config.rs"
    },
    "output": "ok",
    "diff": {
      "path": "src/config.rs",
      "oldText": "a",
      "newText": "b"
    },
    "locations": [
      {
        "path": "src/config.rs",
        "line": 88
      }
    ],
    "rawOutput": {
      "exitCode": 0
    },
    "startedAt": 1700000000000,
    "endedAt": 1700000001200
  },
  {
    "type": "file",
    "blockId": "b4",
    "name": "screenshot.png",
    "mime": "image/png",
    "url": "data:image/png;base64,AAAA"
  }
];

export const usageInfo: UsageInfo = {
  "input": 1200,
  "output": 340,
  "reasoning": 80,
  "cacheRead": 9000,
  "cacheWrite": 100
};

export const configOption: ConfigOption = {
  "id": "model",
  "name": "Model",
  "description": "The model driving the session",
  "category": "model",
  "currentValue": "anthropic/claude-opus-4-8",
  "choices": [
    {
      "value": "anthropic/claude-opus-4-8",
      "name": "Claude Opus 4.8",
      "description": "flagship",
      "group": "Anthropic"
    }
  ]
};

export const chatCommand: ChatCommand = {
  "name": "compress",
  "description": "Compress memory files"
};

export const serverInfo: ServerInfo = {
  "workspace_id": "ws-1",
  "base_url": "http://127.0.0.1:4096",
  "port": 4096
};

export const toolsStatus: ToolsStatus = {
  "mcp": [
    {
      "name": "playwright",
      "status": "failed",
      "error": "auth required"
    }
  ],
  "lsp": [
    {
      "id": "typescript",
      "status": "running"
    }
  ]
};

export const prStatus: PrStatus = {
  "number": 42,
  "url": "https://github.com/acme/repo/pull/42",
  "state": "OPEN",
  "head_branch": "feature/x",
  "head_sha": "abc123",
  "checks": [
    {
      "name": "test",
      "bucket": "failure",
      "state": "FAILURE",
      "url": "https://ci.example/run/1",
      "workflow": "CI"
    }
  ],
  "rollup": "failure"
};

export const prCheck: PrCheck = {
  "name": "test",
  "bucket": "failure",
  "state": "FAILURE",
  "url": "https://ci.example/run/1",
  "workflow": "CI"
};

export const unlinkedTask: UnlinkedTask = {
  "taskId": "t1",
  "title": "Fix header contrast"
};

export const boardSnapshot: BoardSnapshot = {
  "columns": [
    {
      "id": "c1",
      "name": "In progress",
      "role": "active",
      "position": 2048.0,
      "updatedAt": 1700000000000,
      "deletedAt": 1700000000000
    }
  ],
  "tasks": [
    {
      "id": "t1",
      "number": 7,
      "title": "Fix header contrast",
      "description": "On dark mode.",
      "projectId": "p1",
      "columnId": "c1",
      "position": 1024.0,
      "workspaceId": "ws-1",
      "parentId": "t0",
      "dependsOn": [
        "t2"
      ],
      "estimate": 3.0,
      "attachments": [
        {
          "id": "att-1",
          "name": "log.txt",
          "size": 48213,
          "createdAt": 1700000000000
        }
      ],
      "createdAt": 1700000000000,
      "updatedAt": 1700000000000,
      "deletedAt": 1700000000000
    }
  ],
  "estimateUnit": "tshirt"
};

export const activityEntry: ActivityEntry = {
  "id": "act-1",
  "taskId": "t1",
  "kind": "comment",
  "body": "Looks right.",
  "actor": "agent",
  "createdAt": 1700000000000
};

export const chatEntryEvent: ChatEntryEvent = {
  "workspaceId": "ws-1",
  "entry": {
    "type": "assistant",
    "seq": 2,
    "entryId": "a1",
    "status": "completed",
    "origin": "autofix",
    "blocks": [
      {
        "type": "text",
        "blockId": "b1",
        "text": "Fixed the failing test."
      },
      {
        "type": "reasoning",
        "blockId": "b2",
        "text": "The bug is in config parsing…"
      },
      {
        "type": "tool",
        "blockId": "b3",
        "callId": "c3",
        "name": "edit",
        "title": "Edit config.rs",
        "status": "completed",
        "input": {
          "filePath": "src/config.rs"
        },
        "output": "ok",
        "diff": {
          "path": "src/config.rs",
          "oldText": "a",
          "newText": "b"
        },
        "locations": [
          {
            "path": "src/config.rs",
            "line": 88
          }
        ],
        "rawOutput": {
          "exitCode": 0
        },
        "startedAt": 1700000000000,
        "endedAt": 1700000001200
      },
      {
        "type": "file",
        "blockId": "b4",
        "name": "screenshot.png",
        "mime": "image/png",
        "url": "data:image/png;base64,AAAA"
      }
    ],
    "summary": {
      "collapsed": true,
      "stepCount": 3,
      "filesEdited": [
        "src/config.rs"
      ],
      "commandsRun": 1,
      "headline": "Edited 1 file · ran 1 command"
    },
    "usage": {
      "input": 1200,
      "output": 340,
      "reasoning": 80,
      "cacheRead": 9000,
      "cacheWrite": 100
    },
    "startedAt": 1700000000000,
    "endedAt": 1700000009000
  }
};

export const chatBlockEvent: ChatBlockEvent = {
  "workspaceId": "ws-1",
  "entrySeq": 2,
  "block": {
    "type": "tool",
    "blockId": "b3",
    "callId": "c3",
    "name": "edit",
    "title": "Edit config.rs",
    "status": "completed",
    "input": {
      "filePath": "src/config.rs"
    },
    "output": "ok",
    "diff": {
      "path": "src/config.rs",
      "oldText": "a",
      "newText": "b"
    },
    "locations": [
      {
        "path": "src/config.rs",
        "line": 88
      }
    ],
    "rawOutput": {
      "exitCode": 0
    },
    "startedAt": 1700000000000,
    "endedAt": 1700000001200
  }
};

export const chatTurnEvent: ChatTurnEvent = {
  "workspaceId": "ws-1",
  "entrySeq": 2,
  "status": "awaitingPermission",
  "summary": {
    "collapsed": true,
    "stepCount": 3,
    "filesEdited": [
      "src/config.rs"
    ],
    "commandsRun": 1,
    "headline": "Edited 1 file · ran 1 command"
  },
  "usage": {
    "input": 1200,
    "output": 340,
    "reasoning": 80,
    "cacheRead": 9000,
    "cacheWrite": 100
  },
  "endedAt": 1700000009000
};

export const chatPermissionEvent: ChatPermissionEvent = {
  "workspaceId": "ws-1",
  "entrySeq": 2,
  "requestId": "perm-1",
  "toolCallId": "c3",
  "title": "Allow git push?",
  "options": [
    {
      "optionId": "allow",
      "name": "Allow once",
      "kind": "allowOnce"
    }
  ]
};

export const chatConfigEvent: ChatConfigEvent = {
  "workspaceId": "ws-1",
  "options": [
    {
      "id": "model",
      "name": "Model",
      "description": "The model driving the session",
      "category": "model",
      "currentValue": "anthropic/claude-opus-4-8",
      "choices": [
        {
          "value": "anthropic/claude-opus-4-8",
          "name": "Claude Opus 4.8",
          "description": "flagship",
          "group": "Anthropic"
        }
      ]
    }
  ]
};

export const chatResetEvent: ChatResetEvent = {
  "workspaceId": "ws-1"
};

export const chatContextEvent: ChatContextEvent = {
  "workspaceId": "ws-1",
  "used": 12400,
  "max": 200000
};

export const chatCommandsEvent: ChatCommandsEvent = {
  "workspaceId": "ws-1",
  "commands": [
    {
      "name": "compress",
      "description": "Compress memory files"
    }
  ]
};

export const todo: Todo = {
  "content": "Fix newline normalization",
  "status": "in_progress"
};

export const todosPayload: TodosPayload = {
  "workspaceId": "ws-1",
  "todos": [
    {
      "content": "Fix newline normalization",
      "status": "in_progress"
    }
  ]
};

export const gitPayload: GitPayload = {
  "workspaceId": "ws-1",
  "diffStat": {
    "files": 3,
    "insertions": 42,
    "deletions": 7
  },
  "changes": [
    {
      "path": "src/App.tsx",
      "status": "modified",
      "insertions": 10,
      "deletions": 2
    }
  ],
  "branch": "feature/x"
};

export const sessionPayload: SessionPayload = {
  "workspaceId": "ws-1",
  "activity": "working",
  "awaitingInput": true,
  "needsAttention": true,
  "error": "the last turn failed"
};

export const prPayload: PrPayload = {
  "workspaceId": "ws-1",
  "status": {
    "number": 42,
    "url": "https://github.com/acme/repo/pull/42",
    "state": "OPEN",
    "head_branch": "feature/x",
    "head_sha": "abc123",
    "checks": [
      {
        "name": "test",
        "bucket": "failure",
        "state": "FAILURE",
        "url": "https://ci.example/run/1",
        "workflow": "CI"
      }
    ],
    "rollup": "failure"
  },
  "phase": "awaiting_push",
  "attempts": 2,
  "mode": "super",
  "error": "poll failed"
};

export const notifyPayload: NotifyPayload = {
  "workspaceId": "ws-1",
  "kind": "task_review",
  "taskTitle": "Fix header"
};

export const workspaceSetupPayload: WorkspaceSetupPayload = {
  "workspaceId": "ws-1",
  "running": false,
  "ok": true
};

export const accountsPayload: AccountsPayload = {
  "accounts": [
    {
      "id": "github.com/octocat",
      "host": "github.com",
      "login": "octocat",
      "name": "The Octocat",
      "avatarUrl": "https://avatars.example/1",
      "active": true,
      "status": "Sign-in required"
    }
  ]
};

export const reviewInboxPayload: ReviewInboxPayload = {
  "items": [
    {
      "id": "acme/repo#42",
      "accountId": "github.com/octocat",
      "repo": "acme/repo",
      "number": 42,
      "title": "Add rate limiting",
      "url": "https://github.com/acme/repo/pull/42",
      "author": "alice",
      "authorAvatar": "https://avatars.example/2",
      "reason": "review_requested",
      "headRef": "feat/rate-limit",
      "rollup": "pending",
      "isDraft": true,
      "updatedAt": "2026-07-03T09:12:00Z",
      "projectId": "p1"
    }
  ],
  "refreshedAt": 1700000000000,
  "error": "rate limited"
};

export const gitHubLoginEvent: GitHubLoginEvent = {
  "loginId": "login-1",
  "phase": "awaitingCode",
  "code": "WXYZ-1234",
  "url": "https://github.com/login/device",
  "account": {
    "id": "github.com/octocat",
    "host": "github.com",
    "login": "octocat",
    "name": "The Octocat",
    "avatarUrl": "https://avatars.example/1",
    "active": true,
    "status": "Sign-in required"
  },
  "error": "boom"
};

